apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Cogniassist-frontend
  description: Ingress URL for Cogniassist frontend 
spec:
  type: openapi
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: frontend
    servers:
      - url: http://4.224.107.150.nip.io/
    paths:
      /backend:
        get:
          summary: backend
      /discovery:
        get:
          summary: discovery API
    ...
