apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: generated-9efd127f12e1665404e7bbf97d15dcc8e06c8154
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: url
  owner: user:default/guest
