apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ws-codeartifact-repo
  description: AWS CodeArtifact workspace for internal packages
  tags:
    - codeartifact
    - npm
    - internal
  annotations:
    aws.amazon.com/codeartifact-domain: techstackrepo
    aws.amazon.com/codeartifact-repo: techstack
    aws.amazon.com/codeartifact-region: eu-north-1
spec:
  type: library
  lifecycle: production
  owner: team-infra
