apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: VIVEK-cogniwide-repo
  description: Event managment system repository
spec:
  type: service
  lifecycle: experimental
  owner: VIVEK-cogniwide
