apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  annotations:
    jenkins.io/job-full-name: 'folder/job-name'
    jenkins.io/github-folder: 'organization/project-name'
spec:
  type: service
  lifecycle: experimental
  owner: user:VIVEK-cogniwide
