apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-azure-ad-user
  title: Create an Azure AD User
  description: Template for creating an Azure AD user using Terraform
  tags: ['azure', 'terraform', 'aad']
spec:
  owner: guests
  type: service
  targets:
    - https://github.com/VIVEK-cogniwide/terraform_cloud/tree/main/terraform_cloud_practicals/IAC/terraform/terraform-Modules/azure_ad

  parameters:
    - title: Azure AD User Configuration
      required:
         - displayName
         - mailNickname
         - action
      properties:
        displayName:
          title: Display Name
          type: string
          description: Name of the Azure AD user

        mailNickname:
          title: Mail Nickname
          type: string
          description: Mail alias for the user

        action:
          title: Action
          type: string
          description: Select whether to apply (create) or destroy the user
          enum:
            - apply
            - destroy

    - title: Choose a Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    # Fetch Terraform templates for Azure AD User
    - id: fetch-template
      name: Fetch Terraform Code
      action: fetch:template
      input:
        url: "https://github.com/VIVEK-cogniwide/terraform_cloud/tree/main/terraform_cloud_practicals/IAC/terraform/terraform-Modules/azure_ad"
        values:
          displayName: ${{ parameters.displayName }}
          mailNickname: ${{ parameters.mailNickname }}

output:
    links:
      - title: Open in Backstage Catalog
        icon: catalog
       
