apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe
  description: Cogniwide employee
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@cogniwide.com
    picture: https://sl.bing.net/d4ip5smUfT2
  memberOf: [guests]
